### ISSUE TITLE
Question on EFI Preparation

### ISSUE THREAD

**Issue by aliyektaie** [jackhanyuan/Dell-XPS15-7590-Hackintosh#1]
Hi,

Thanks for preparing this EFI!
I am currently using this EFI (https://github.com/1nferious/Dell-XPS-15-7590-MacOS-Ventura--13.0--Hackintosh) which is similar to yours except it is for Intel Wifi, not the 1830, and it is working on my laptop.
I downloaded your EFI and changed the serial, mlb and uuid to match my previous EFI to prevent the keychain to break. I ran the commands in grub (setup_var ....). I tried with & without the high DPI config on both DW1830 and DW1820A.
At every try, macOS 13.0.1 boots, but in the middle of loading right after the brightness of LCD changes, the screen becomes black. It is not turned off, but it is completely black.
Since your EFI has been tested and I see the same behavior in every case, I'm sure I'm missing a step. Could you please tell me if you see any mistake that I'm doing?

**Comment by jackhanyuan** [comment]
With the limited information you provided, I'm not sure what is causing this issue. You can add `-v` in `boot-args` to turn on verbose mode in `config.plist` to view detailed problems. In addition, my display is `1080p without touch`. I don’t know if your display is consistent. If it is `4k`, you need to modify your `config.plist`, find `dpcd-max-link-rate` and change its value to `FAAAAA==`

**Comment by laobei** [comment]
> 
按照说明修改了这个值， 还是黑屏， 已经启动到登录界面了， 回车有空操作的声音， 屏幕是黑的 所以-v也看不到。 我的屏幕是4k触摸屏
Find dpcd-max-link-rate and change its value to FAAAAA==Find dpcd-max-link-rate and change its value to FAAAAA==
