### ISSUE TITLE
正在关注更新，有空是否可以支持下4k屏

### ISSUE THREAD

**Issue by laobei** [jackhanyuan/Dell-XPS15-7590-Hackintosh#2]

**Comment by jackhanyuan** [comment]
I don't have a 4K OLED screen, so I can't test it, you can refer to [sash11/Dell-XPS15-7590](https://github.com/sash11/Dell-XPS15-7590) and [Liyunlock/DELL-XPS-15-7590-4K-Touchscreen_OpenCore_Hackintosh](https://github.com/Liyunlock/DELL-XPS-15-7590-4K-Touchscreen_OpenCore_Hackintosh).

**Comment by laobei** [comment]
> I don't have a 4K OLED screen, so I can't test it, you can refer to [sash11/Dell-XPS15-7590](https://github.com/sash11/Dell-XPS15-7590) and [Liyunlock/DELL-XPS-15-7590-4K-Touchscreen_OpenCore_Hackintosh](https://github.com/Liyunlock/DELL-XPS-15-7590-4K-Touchscreen_OpenCore_Hackintosh).

无法启动，不知道是不是因为bios版本不一样导致的，我的bios和你的一样1.20

**Comment by jackhanyuan** [comment]
你可以试试G.（mail：basicemailext@protonmail.com）提供的[4k-OLED](https://github.com/jackhanyuan/Dell-XPS15-7590-Hackintosh/tree/4k-OLED)分支。

**Comment by laobei** [comment]
> 你可以试试G.（mail：[basicemailext@protonmail.com](mailto:basicemailext@protonmail.com)）提供的[4k-OLED](https://github.com/jackhanyuan/Dell-XPS15-7590-Hackintosh/tree/4k-OLED)分支。

这个可以使用, 正常使用, 蓝牙能开不能用, 一直连不上, dw1830

蓝牙控制器：
  地址：	18:4F:32:F7:89:32
  状态：	打开
  芯片组：	THIRD_PARTY_DONGLE
  可被发现：	关闭
  固件版本：	v8453 c4096
  支持的服务：	0x382039 < HFP AVRCP A2DP HID Braille AACP GATT SerialPort >
  传输：	USB
  供应商ID：	0x004C (Apple)
  未连接：
  vivian：
  地址：	88:A9:B7:86:4D:93
