### ISSUE TITLE
Wifi is not working

### ISSUE THREAD

**Issue by abdulrahmanali1** [jackhanyuan/Dell-XPS15-7590-Hackintosh#4]
I'm currently using this files https://github.com/xxxzc/xps15-9570-macos on my XPS15-7590 and everything is working fine, but this file are not made for XPS15-7590. when I found you repo i tried but for some reason wifi is not working but Bluetooth is working fine.

**Comment by jackhanyuan** [comment]
Ok, different hardware and system versions may cause problems, my EFI is only verified on my XPS-7590, https://github.com/xxxzc/xps15-9570-macos is an excellent repository, XPS-9570 and XPS -7590 doesn't make much difference, you can keep using it if it's OK.

**Comment by jackhanyuan** [comment]
I also had occasional wifi issues and a reboot fixed it.
