### ISSUE TITLE
Where is Bios 1.24 

### ISSUE THREAD

**Issue by 1alessandro1** [jackhanyuan/Dell-XPS15-7590-Hackintosh#8]
Hello!
First of all, thank you for sharing your work. The thing that surprised me the most is the attention to hidden BIOS options... 

However, I can't find the exact 1.24 version of your BIOS. Can you please share a link to it?

From documentation:

> BIOS version: 1.24.0 

![image](https://github.com/jackhanyuan/Dell-XPS15-7590-Hackintosh/assets/46293832/90901dc2-546e-49e7-8585-aadb7b6747cd)

This is the latest version I found (1.22) : https://dl.dell.com/FOLDER10601904M/1/Inspiron_7590_7591_Vostro_7590_v1.22.0.exe

**Comment by jackhanyuan** [comment]
This repo is for XPS 7590, not Inspiron 7590. The download link for XPS 7590 BIOS 1.24.0 is here.

https://dl.dell.com/FOLDER10591874M/1/XPS_7590_1.24.0.exe

In fact, the BIOS version is not so strict, and the test shows that 1.19+ is OK.
